### ISSUE TITLE
minor issues with linux zip

### ISSUE THREAD

**Issue by bmesuere** [compomics/pladipus#1]
Two small suggestions:

* The zip file extracts a folder starting with a `.` meaning it's hidden. While this may be on purpose, it's unexpected behaviour. As an advanced unix user, I tried to extract the zip 3 times wondering where the contents was.

* The zip file is huge. Many of the bundled tools include sample data that are not needed for the purpose of pladipus. Consider removing them to reduce the file size.

**Comment by kverhegg** [comment]
Hey there ! Thanks for the feedback. We're looking for a solution as fast as we can to resolve this. In future versions, the unzip will skip the .compomics path and just unzip a pladipus folder in the home folder.

As for the zip file, it is huge and I am sorry that I forgot to remove the example files. This also will be resolved pretty soon !

**Comment by kverhegg** [comment]
A newer version is now online with a new installation location and zip files without the example materials for the external tools. The new path is : 

`$USER_HOME/pladipus/`

Thanks for the feedback !
