### ISSUE TITLE
Installing Pladipus

### ISSUE THREAD

**Issue by Nyaradzo** [compomics/pladipus#2]
I have been trying to install pladipus on my machine. When I run it the first time I was getting the MySQL error Could not create user: com.mysdl.jbdc.exceptions.jdbc4.communicationsException:communication link failure.
I reinstalled mySQL and tried again but got the error "The ActiveMQ Server could not be reached.

I have subsequently looked for the my.ini file as suggested but cannot find it.  I installed mysql 5.7.11

please help
Thanks

**Comment by kverhegg** [comment]
Hello !

I am currently on sick leave, but I'll try to look into it.
Have you started the ActiveMQ server prior to launching pladipus? If not, could you let me know how you have installed pladipus (using the wizard or the zipped package)?

Kind regards,


Kenneth

**Comment by Thys3Potgieter** [comment]
Hi, the links to the default installers appear to broken, only the zipped package is available. Are there specific instructions for compiling from source? 

Thanks!

Thys

**Comment by kverhegg** [comment]
There have been some university network related issues on the server hosting the installer and the packages. I will look into this asap and make sure the tool can be easily downloaded once again!

Sorry for the inconvenience, I'll try to deliver an updated installer next week.

**Comment by Thys3Potgieter** [comment]
Thank you :)

**Comment by KennethVerheggen** [comment]
@Thys3Potgieter : The issues surrounding the download links are now resolved. 
@Nyaradzo : Could you let me know if you need further assistance please?

**Comment by kverhegg** [comment]
I have closed the issue due to no further feedback on the topic. Please do contact me if you'd want further assistance !
