### ISSUE TITLE
mzid -> MoFF converter class

### ISSUE THREAD

**Issue by Stortebecker** [compomics/pladipus#4]
A while ago @kverhegg mentioned here https://github.com/compomics/moFF/issues/2 that the converter is not fully tested. Is it fully functional now?

**Comment by Maux82** [comment]
Hi ,

In order to avoid the use of external piece of sw in the conversion between PeptideShaker and moFF we are working on a solution inside moFF just using the standard export  of PeptideShaker.
Check [compomics/moFF#2](https://github.com/compomics/moFF/issues/2) for furher update
