### ISSUE TITLE
Download link and Maven dependencies don't work

### ISSUE THREAD

**Issue by CarlosHorro** [compomics/pladipus#5]
Hi,

I was trying to use moFF-gui, and when I build it I get this error:

Failed to execute goal on project moff-gui: Could not resolve dependencies for project com.compomics:moff-gui:jar:1.1.2: Failure to find com.compomics:Pladipus-moff:jar:1.2.2 in http://genesis.UGent.be/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of genesis-maven2-repository has elapsed or updates are forced -> [Help 1]

So it doesn't find Pladipus-moff:jar:1.2.2 library.

I've also tried to download the .jar from the download links provided at https://github.com/compomics/pladipus ,  but they (http://genesis.ugent.be/pladipus/download/Pladipus-installer-1.2.1.jar , or http://genesis.ugent.be/pladipus/download/Pladipus-installer-1.1.0.jar ) are broken:

Not Found
The requested URL /pladipus/download/Pladipus-installer-1.2.1.jar was not found on this server.

Finally, I've tried to build by myself Pladypus-moFF, but I get again another error:

Failed to execute goal on project Pladipus-moff: Could not resolve dependencies for project com.compomics:Pladipus-moff:jar:1.2.2: The following artifacts could not be resolved: com.compomics:Pladipus-core:jar:1.2.1, com.compomics:Pladipus-search:jar:1.2.1: Could not find artifact com.compomics:Pladipus-core:jar:1.2.1 in genesis-maven2-repository (http://genesis.UGent.be/maven2) -> [Help 1]

So it seems that in this case Maven doesn't found Pladipus-core.jar:1.2.1.
Could you help me with these errors, please?

Greetings,
Carlos

**Comment by nielshulstaert** [comment]
Hi Carlos,

Thanks for pointing this out! I've deployed pladipus-moff 1.2.2 to our maven server and you should be able to build moff-gui now.

Best regards,

Niels

**Comment by CarlosHorro** [comment]
Hi Niels,

Thank you very much, jar building is now working.
By the way, only as a suggestion as I don't need it now, I would also recommend to fix the download link to the .jar in the main doc page.

Greetings,
Carlos

**Comment by nielshulstaert** [comment]
Hi Carlos,

The download link on the moff-gui page seems to be working, which page do you mean?

Best regards,

Niels

**Comment by CarlosHorro** [comment]
Hi Niels,

I meant, at the bottom of the main README.md doc file in this repository: 
https://github.com/compomics/pladipus

the download button "Download installer" (which points to a broken link http://genesis.ugent.be/pladipus/download/Pladipus-installer-1.2.1.jar")  and also the link in the phrase "We strongly recommend using the [installer](http://genesis.ugent.be/pladipus/download/Pladipus-installer-1.1.0.jar)".

Greetings,
Carlos

**Comment by nielshulstaert** [comment]
Hi Carlos,

The links are working again. Thanks again for pointing this out.

Best regards,

Niels
